### 现有分析（问号代表不确定）
各个幻想体系的构筑，一般通过在现实世界的基础上附加创造，有如下三个层次
#### 最低层次：新增物质或更改现有物质（更深层可能不自洽）
##### mass effect（详细见《质量效应银河大百科》）
>* 零号元素（与实际的不一样）：电流的作用下产生的暗能量场，在能量场中物质的质量会降低或增加。
>   * FTL技术：在接通负电流后产生质量弱化场中，物质的质量将被大大的降低。而使得货物运输变得容易，并且可以进行超光速飞行。
>   * 护盾和武器技术：在接通正电流的情况下会产生质量强化场，质量强化场可以用于航天器规避太空中的太空碎片，并且可以产生抵御动能攻击的护盾反之可以加强武器威力。
>   * 异能：异能者使用大脑电脉冲作用于神经系统中的许多零素瘤来操控质量效应场。增幅器使异能者能调谐零素瘤，形成更大更强具有实用意义的效应场。异能者必须能有意识地控制神经系统，发送特定的电脉冲到附着于神经系统的零素瘤。他们通过生物反馈装置和物理助记装置帮助学习使用植入物和增幅器。特定的姿势或肌肉运动会对神经造成适当的刺激来发动某种技能。3个分支：TELEKINESIS（心灵促动）能够使用质量降低力场来漂浮和推动物体.而加重质量的 KINETIC FIELDS（动力场）能够阻挡和定住物体. DISTORTION（心灵曲解）用来迅速转换质量力场从而达到撕碎物体的目的。
>
##### death note
>
>
#### 第二层次：新增理论（重新推演世界变化，公理间可能存在矛盾，如zf增加c？steampunk？）
##### bioshock
> * 新增体系——精神：通过基因注射改造的超能力能产生类似魔法的能力
>   * 整个城市社会的变化
> * 新增体系——平行世界：可以被某些能力，机器影响？？
>
##### arcanum of steamworks and magick obscura
> * 新增体系——魔法：与科学对立的一种体系，由人的能量发生？
>   * 魔法与科学的冲突：蒸汽时代
>   * 魔法对世界的影响
>
##### 死亡台球？？？
> * 新增体系——灵魂：人是由灵魂和肉体组成
>   * 死后的世界
>   * 
>
##### chaos;head:noah
> * 新增体系——妄想：妄想的力量可以影响后续事件的发展
>   * 世界的变化
>
#### 最高层次：修改现有理论（完全构造新世界，不自洽可能？欧几非欧几？）
##### dark souls（分析来源：魂学家们）
> * 火和魂：魂——能量源泉，混沌；火——精炼魂并产生力量，秩序
>   * 火诞生前：阳光提供能源进入雾气（也就成为一切魂力的来源），岩石巨树吸收雾气中的能源，生长在灰色岩石上（或者说它们本来就是灰色岩石的一部分，吸收了能量就能长起来），而永生的巨龙是吃岩石为生的。黑暗之魂则存在于深渊，只是没有光明也就没有明确的意识，是深渊里形体都不明确之物。
>   * 火诞生后（火不是天雷劈出来的，也不是地上烧起来的，而是在很深很深的地下黑暗中燃烧起来的，换句话说，最初火就是深渊诞生）：火让一切有了分别，冷与热，光与暗，才有了基本的秩序和法则。深渊初火从黑暗之魂中催生王者，王者屠龙开启火时代，古龙灭绝后第一次火时代的终结也就迟早不可避免，葛温舍身传火，但第二次火时代也很快结束，于是太阳神系后裔纷纷逃离王城，只剩下暗月神创造活死人诅咒开始传火阴谋。
> 
### 催生问题
* 是否将三层修改为两层（新增物质/理论；修改物质/理论）
* 增加某基因/细胞/结构等的生物类幻想（如强殖装甲），如何判断生物是否合理（在现有的世界内）
